### PR TITLE
make bower export 'underscoreDB' variable, instead of using _.mixin method directly 

### PR DESCRIPTION
**Pull request by ironhee**
Make browser.js export 'underscoreDB' in global scope as variable.
Before, browser.js called _.mixin method directly. so the user could not choose whether '_' refers to underscore or lodash.

### CODE REVIEW

**Comment by typicode** [comment]
Hi @ironhee ,

Not sure to understand.

You mean, the user could not choose whether '_' refers to underscore or lodash.
But, usually you load either lodash or underscore in the browser?

**Comment by ironhee** [comment]
Yes. I usually load either lodash or underscore in the browser. 
but I think for the sake of symmetry with node.js, bower package should export mixin variable and turn over the responsibility of calling _.mixin to user.
At least exporting mixin variable in global scope can be pursued more symmetry with node.

**Comment by typicode** [comment]
Unfortunately, there's no best/official practice for writing libraries for Underscore (at least not aware of).

I understand the symmetry part but other libraries just  seem to automatically use `_.mixin` when used in the browser. For example, https://github.com/documentcloud/underscore-contrib.

The only exception would be https://github.com/epeli/underscore.string but I guess it's because it doesn't actually depend on underscore.

So, following a principle of least surprise, I think it's better and simpler to keep:

```html
<script src="underscore.js" type="text/javascript"></script>
<script src="underscore-db.js" type="text/javascript"></script>
```

If things change, I'll be happy to update the project.

Thanks again for the PR.

**Comment by ironhee** [comment]
thank you :D. 
After read your comment, I also agree about your opinion. It's better and simpler way for now.

I always conveniently use your libraries. 
Thank you :D 

Have a good day~~~

**Pull request closed without merging**
